services:
  - type: web
    name: wasal-backend
    env: node
    buildCommand: cd back-end && npm install --legacy-peer-deps
    startCommand: cd back-end && npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://username:password@cluster.mongodb.net/wasal
